---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: react-nginx
  namespace: staging
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-nginx
  targetCPUUtilizationPercentage: 50
  